import FWCore.ParameterSet.Config as cms

defaultObjectParameters = cms.PSet(
    ElectronEtaCrackMinimum           = cms.untracked.double(1.4442),
    ElectronEtaCrackMaximum           = cms.untracked.double(1.5660),
    ElectronMaximumDeltaZ             = cms.untracked.double(1.0),
    ElectronMaximumD0BS               = cms.untracked.double(0.2),
    ElectronMaximumIsolation          = cms.untracked.double(0.1),
    ElectronMinimumET                 = cms.untracked.double(30.0),
    ElectronMaximumEta                = cms.untracked.double(2.5),
    UseElectronID                     = cms.untracked.bool(True),
    ElectronMaximumMissingInnerLayers = cms.untracked.int32(0),
    ElectronConversionDist            = cms.untracked.double(0.02),
    ElectronConversionDcot            = cms.untracked.double(0.02),
    MuonVetoPT                        = cms.untracked.double(10.),
    MuonVetoEta                       = cms.untracked.double(2.5),
    MuonVetoIsolation                 = cms.untracked.double(0.2),
    LooseElectronMinimumET            = cms.untracked.double(20.),
    LooseElectronMaximumEta           = cms.untracked.double(2.5),
    LooseElectronMaximumIsolation     = cms.untracked.double(1.0),
    MuonMaximumDxy                    = cms.untracked.double(0.2),
    #MuonMaximumD0BS                   = cms.untracked.double(0.02),
    MuonMaximumDeltaZ                 = cms.untracked.double(0.5),
    MuonMaximumNormalizedChi2         = cms.untracked.double(10.),
    MuonMinimumTrackerHits            = cms.untracked.int32(5),
    MuonMinimumPixelHits              = cms.untracked.int32(0),
    MuonMinimumMatched                = cms.untracked.int32(1),
    MuonMinimumMuHits                 = cms.untracked.int32(0),
    MuonMaximumIsolation              = cms.untracked.double(0.12),
    MuonMinimumPT                     = cms.untracked.double(26.),
    MuonMaximumEta                    = cms.untracked.double(2.1),
    ElectronVetoET                    = cms.untracked.double(20.),
    ElectronVetoEta                   = cms.untracked.double(2.5),
    ElectronVetoIsolation             = cms.untracked.double(0.2),
    UsePUCorrectedIsolation           = cms.untracked.bool(False),
    UsePFIsolation                    = cms.untracked.bool(True),
    JetMinimumPT                      = cms.untracked.double(30.),
    JetMaximumEta                     = cms.untracked.double(2.5),
    JetUseID                          = cms.untracked.bool(False),
    JetMinimumConstituents            = cms.untracked.int32(1),
    JetMinimumChargedMultiplicity     = cms.untracked.int32(0),
    JetMaximumCEF                     = cms.untracked.double(0.99),
    JetMaximumNHF                     = cms.untracked.double(0.99),
    JetMaximumNEF                     = cms.untracked.double(0.99),
    JetMinimumCHF                     = cms.untracked.double(0.),
    JetEtaSwitch                      = cms.untracked.double(2.4),
    FirstVertexOnly                   = cms.untracked.bool(True),
    VertexMinimumNDOF                 = cms.untracked.double(4.),
    VertexMaximumZ                    = cms.untracked.double(24.),
    VertexMaximumRho                  = cms.untracked.double(2.),
    Debug                             = cms.untracked.bool(False)
    )


